		<div class="brands-container">
            <img src="<?php echo $this->getSkinUrl('images/tpay/visa.svg')?>" height="36" border="0" alt="" style="display: inline; margin-right: 5px;">
			<img src="<?php echo $this->getSkinUrl('images/tpay/mastercard.svg')?>" height="36" border="0" alt="" style="display: inline; margin-right: 5px;">
			<img src="<?php echo $this->getSkinUrl('images/tpay/secure.svg')?>" height="36" border="0" alt="" style="display: inline; margin-left: 100px;">
			<img src="<?php echo $this->getSkinUrl('images/tpay/twispay.svg')?>" height="36" border="0" alt="" style="display: inline;">
		</div>
        