<br>
<br>
<!-- We can peacefully add some nice redirection here with some intentional delay -->
<div style="text-align:center">
  <h2>We are redirecting you to payment. Please wait ...</h2>
  <br>
  <img src="http://i.imgur.com/KUJoe.gif" />
</div>

<!-- Hidden form to submit -->
<form action="<?= $url; ?>" method="POST" accept-charset="UTF-8" id="twispay_payment_form">
  <input type="hidden" name="jsonRequest" value="<?= $jsonRequest; ?>">
  <input type="hidden" name="checksum" value="<?= $checksum; ?>">
</form>

<script type="text/javascript">document.getElementById("twispay_payment_form").submit();</script>
